### ISSUE TITLE
connect mongodb cluster error, can you provide a case? Thank you.

### ISSUE THREAD

**Issue by yuanshanhshan** [rookie-ninja/rk-boot#112]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dongxuny** [comment]
@yuanshanhshan Hi，The official docs for rk-db/mongodb is missing currently，I will add the official docs ASAP。

**Comment by dongxuny** [comment]
@yuanshanhshan Hi, MongoDB docs added into https://docs.rkdev.info/docs/rk-boot/getting-started/database/mongodb/ official site.

If there are still errors occur, please paste your errors in this thread, I will look into that. Thanks

**Comment by yuanshanhshan** [comment]
Thanks
